$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
      responsive:{
          0:{
              items:2
          },
          600:{
              items:4
          },
          1000:{
              items:6
          }
      }
  });